
let questions = [
    {
    numb: 1,
    question: "Who is known as father of Java Programming Language? ",
    answer: "James Gosling",
    options: [
      "Charel Babbage",
      "James Gosling",
      "Blais Pascal",
      "M. P Java"
    ]
  },
    {
    numb: 2,
    question: "In java control statements break, continue, return, try-catch-finally and assert belongs to? ",
    answer: "Transfer statements",
    options: [
      "Selection statements",
      "Loop Statements",
      "Transfer statements",
      "Pause Statement"
    ]
  },
    {
    numb: 3,
    question: "Which provides runtime environment for java byte code to be executed? ",
    answer: "JVM",
    options: [
      "JDK",
      "JRE",
      "JAVAC",
      "JVM"
    ]
  },
    {
    numb: 4,
    question: "What does SQL stand for?",
    answer: "Structured Query Language",
    options: [
      "Stylish Question Language",
      "Stylesheet Query Language",
      "Statement Question Language",
      "Structured Query Language"
    ]
  },
    {
    numb: 5,
    question: "What is byte code in Java?",
    answer: "Code generated by a Java compiler ",
    options: [
      "Name of Java source code file",
      "Code generated by a Java compiler ",
      "Block of code written inside a class",
      "i dont know"
    ]
  },
 
];